version: '3.8'
services:
  vuejs:
    container_name: frontend
    build:
      context: vue-project/
      dockerfile: Dockerfile
    volumes:
      - ./vue-project:/app
      - /app/node_modules
    ports:
      - "5173:5173"
